"""empty message

Revision ID: 24adb3364e70
Revises: 
Create Date: 2025-09-20 19:25:56.778671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24adb3364e70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('account', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=16), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('account')
    )
    op.create_table('admins',
    sa.Column('account', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['account'], ['users.account'], ),
    sa.PrimaryKeyConstraint('account')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.String(length=9), nullable=False),
    sa.Column('author_name', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('upvote', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.account'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.String(length=9), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('upvote', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.account'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_issue_id'), ['issue_id'], unique=False)

    op.create_table('issue_labels',
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('issue_id', 'label_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_labels')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_issue_id'))

    op.drop_table('comments')
    op.drop_table('issues')
    op.drop_table('admins')
    op.drop_table('users')
    op.drop_table('labels')
    # ### end Alembic commands ###
