"""empty message

Revision ID: 4c1b08ece918
Revises: f9b6a2b3f9f6
Create Date: 2025-09-20 23:40:20.615868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1b08ece918'
down_revision = 'f9b6a2b3f9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=64), nullable=True))
        batch_op.alter_column('author_id',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=16),
               existing_nullable=False)
        batch_op.drop_column('labels')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labels', sa.VARCHAR(length=64), nullable=True))
        batch_op.alter_column('author_id',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.drop_column('label')

    # ### end Alembic commands ###
