"""empty message

Revision ID: a027ca1ed02a
Revises: 
Create Date: 2025-09-20 17:53:20.263634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a027ca1ed02a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('account', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=16), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('account')
    )
    op.create_table('admins',
    sa.Column('account', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['account'], ['users.account'], ),
    sa.PrimaryKeyConstraint('account')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    op.drop_table('users')
    # ### end Alembic commands ###
